"""add actress profile extension (rich columns + actress_images, actress_aliases tables)

Revision ID: d5a638a6528e
Revises: 0002_add_products_video_files
Create Date: 2026-06-20

This migration is **additive only** for actresses table and adds two new tables.
Other schema diffs detected by autogenerate (type changes, dropped indexes) were
intentionally excluded to prevent unintended changes to existing tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a638a6528e'
down_revision: Union[str, Sequence[str], None] = '0002_add_products_video_files'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Actress profile extension (columns already exist from model update).
    Only create new tables + index + version bump.
    """
    # Columns already present (schema check confirmed)
    op.create_index(op.f('ix_actresses_name_ko'), 'actresses', ['name_ko'], unique=False, if_not_exists=True)

    # New tables
    op.create_table(
        'actress_images',
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.Column('actress_id', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=False),
        sa.Column('is_profile', sa.Boolean(), nullable=True, server_default=sa.text('0')),
        sa.Column('sort_order', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('caption', sa.Text(), nullable=True),
        sa.Column('added_at', sa.DateTime(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.ForeignKeyConstraint(['actress_id'], ['actresses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('ix_actress_images_actress_id', 'actress_images', ['actress_id'], unique=False)

    op.create_table(
        'actress_aliases',
        sa.Column('alias_id', sa.Integer(), nullable=False),
        sa.Column('actress_id', sa.Integer(), nullable=True),
        sa.Column('alias_name', sa.Text(), nullable=False),
        sa.Column('alias_type', sa.Text(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True, server_default=sa.text('0')),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.ForeignKeyConstraint(['actress_id'], ['actresses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index('ix_actress_aliases_name', 'actress_aliases', ['alias_name'], unique=False)
    op.create_index('ix_actress_aliases_actress_id', 'actress_aliases', ['actress_id'], unique=False)

    # Update schema version
    conn = op.get_bind()
    current = conn.exec_driver_sql("PRAGMA user_version").scalar() or 0
    if int(current) < 11:
        conn.exec_driver_sql("PRAGMA user_version = 11")
    print('[Migration] Actress profile tables created successfully (columns were pre-existing).')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_watch_history_watch_later'), 'watch_history', ['watch_later', 'watch_later_added_at'], unique=False)
    op.alter_column('watch_history', 'watch_later',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_products_folder_path'), 'products', ['folder_path'], unique=False)
    op.alter_column('products', 'folder_path',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_jav_metadata_updated_at'), 'jav_metadata', ['updated_at'], unique=False)
    op.create_index(op.f('idx_jav_metadata_release_date'), 'jav_metadata', ['release_date'], unique=False)
    op.create_index(op.f('idx_jav_metadata_folder_path'), 'jav_metadata', ['folder_path'], unique=False)
    op.create_index(op.f('idx_jav_metadata_analysis_status'), 'jav_metadata', ['analysis_status'], unique=False)
    op.create_index(op.f('idx_jav_favorite_score'), 'jav_metadata', ['favorite_score'], unique=False)
    op.alter_column('jav_metadata', 'folder_path',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jav_metadata', 'is_mopa',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('jav_metadata', 'is_hardcoded',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_fav_hist_pc_time'), 'favorite_score_history', ['product_code', 'observed_at'], unique=False)
    op.drop_index(op.f('ix_actresses_name_ko'), table_name='actresses')
    op.drop_column('actresses', 'memo')
    op.drop_column('actresses', 'last_watched')
    op.drop_column('actresses', 'watch_count')
    op.drop_column('actresses', 'strong_reaction_count')
    op.drop_column('actresses', 'favorite_intensity')
    op.drop_column('actresses', 'is_favorite')
    op.drop_column('actresses', 'agency')
    op.drop_column('actresses', 'debut_date')
    op.drop_column('actresses', 'cup_size')
    op.drop_column('actresses', 'hip')
    op.drop_column('actresses', 'waist')
    op.drop_column('actresses', 'bust')
    op.drop_column('actresses', 'height')
    op.drop_column('actresses', 'birth_date')
    op.drop_column('actresses', 'profile_text')
    op.drop_column('actresses', 'user_score')
    op.drop_column('actresses', 'genres')
    op.drop_column('actresses', 'profile_image_url')
    op.drop_column('actresses', 'name_en')
    op.drop_column('actresses', 'name_ko')
    op.drop_column('actresses', 'name_ja')
    # ### end Alembic commands ###
